[[headers]]
  for = "/*"
  [headers.values]
     Access-Control-Allow-Origin = "*"
     
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[functions."lastFmFetch"]
  schedule = "@weekly"